ALT/ALT.Web.GamePlayer/Controllers/GameHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALT.Web.GamePlayer.Controllers
{
    using Core;
    using ALT.Web.GamePlayer.Models;
    using System.Threading.Tasks;
    using PagedList;

    public class GameHistoryController : BaseController
    {
        // GET: Game
        public async Task<ActionResult> Index(int? InstructorPage, DateTime? startDate, DateTime? endDate, int? totalRecords, string gamecode = null)
        {
            var pageNumber = InstructorPage ?? 1;
            DateTime start = startDate == null ? DateTime.Now : (DateTime)startDate;
            DateTime end = endDate == null ? DateTime.Now : (DateTime)endDate;
            totalRecords = totalRecords == null ? 50 : (int)totalRecords;
            var gameHistories = new GameHistoryViewModel()
            {
                Username = ALT.Web.GamePlayer.Core.AuthManager.AuthIdentity.Username,
                StartDate = start,
                EndDate = end,
                TotalRecords = (int)totalRecords,
                CurrentPage = 1,
                GameCode = gamecode,
                GameHistory = new Common.Helpers.PagedList<Common.Models.GameHistoryResp> { }
            };

            gameHistories.GameHistory = await this.game.GameTransactionHistory(gameHistories.Username, gameHistories.StartDate, gameHistories.EndDate, gameHistories.GameCode, pageNumber, TotalItemPerPages, gameHistories.TotalRecords);

            ViewBag.TotalPage = gameHistories.GameHistory != null ? gameHistories.GameHistory.TotalPages : 0;

            var getGames = await this.game.GetAllGame(null, IncludedSetting, Publisher, Platforms);
            ViewBag.GetAllGames = getGames;
            ViewBag.TotalItemPerPages = TotalItemPerPages;

            return View(gameHistories);
        }

        [HttpPost]
        public async Task<ActionResult> Index(int? InstructorPage, GameHistoryViewModel request, string gamecode = null)
        {
            var getGames = await this.game.GetAllGame(null, IncludedSetting, Publisher, Platforms);
            ViewBag.GetAllGames = getGames;
            request.GameHistory = await this.game.GameTransactionHistory(request.Username, request.StartDate, request.EndDate, request.GameCode, 1, TotalItemPerPages, request.TotalRecords);

            ViewBag.TotalPage = request.GameHistory != null ? request.GameHistory.TotalPages : 0;
            ViewBag.TotalItemPerPages = TotalItemPerPages;

            return View(request);
        }

        public GameHistoryController(IGame game)
        {
            this.game = game;
        }
        private readonly IGame game;

        public readonly static int TotalItemPerPages = 50;
        private static readonly string Publisher = "ALT";
        private static readonly string Platforms = "Web";
        private static readonly bool IncludedSetting = true;

    }
}

ALT/ALT.Web.GamePlayer/Controllers/HomeController.cs
using ALT.Common.Models;
using ALT.Web.GamePlayer.Core;
using ALT.Web.GamePlayer.Infrastructer;
using ALT.Web.GamePlayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace ALT.Web.GamePlayer.Controllers
{
    public class HomeController : BaseController
    {
        IList<GameResp> getAllGame;
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [AjaxOnlyAttribute]
        public async Task<ActionResult> GetAllGamne()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                string gamecode = "";
                getAllGame = await this.game.GetAllGame(gamecode, IncludedSetting, Publisher, Platforms);

                if (getAllGame == null)
                {
                    return RedirectToAction("Login", "Account");
                }
            }

            return Json(getAllGame, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Game(string gamecode)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                GameCommonViewModel gameCommonViewModel = new GameCommonViewModel();
                IList<GameSettingResp> getGameSetting = await this.game.GameSetting(gamecode, Publisher, Platforms);
                GameAccessViewModel accessGame = new GameAccessViewModel();

                gameCommonViewModel.GameSetting = getGameSetting.Select(c => new GameSettingViewModel
                {
                    GameCode = c.GameCode,
                    Publisher = c.Publisher,
                    Platform = c.Platform,
                    DowloadURL = c.DowloadURL,
                    GameHash = c.GameHash,
                    GameKey = c.GameKey,
                    GameHeader = c.GameHeader,
                    Enable = c.Enable,
                    IsHot = c.IsHot,
                    IsNew = c.IsNew,
                    Rate = c.Rate,
                    Type = c.Type,
                    Width = c.Width,
                    Domain = c.Domain,
                    Height = c.Height,
                    Port = c.Port
                }).FirstOrDefault();

                accessGame.Username = AuthManager.AuthIdentity.Username;
                accessGame.Points = AuthManager.AuthIdentity.Points;
                accessGame.IPHashKey = AuthManager.AuthIdentity.IPHashKey;
                accessGame.PointRate = AuthManager.AuthIdentity.PointRate;
                accessGame.Secret = AuthManager.AuthIdentity.Secret;
                accessGame.SessionCode = AuthManager.AuthIdentity.SessionCode;
                accessGame.TokenMobile = AuthManager.AuthIdentity.TokenMobile;

                gameCommonViewModel.GameAccess = accessGame;

                return View(gameCommonViewModel);
            }
        }

        [HttpGet]
        [AjaxOnlyAttribute]
        public async Task<JsonResult> GetBalanceByOcode(string sessionOcode)
        {
            var result = await this.game.GetBalanceOfMemberByOcode(sessionOcode);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public HomeController(IGame game)
        {
            this.game = game;
        }

        private readonly IGame game;
        private static readonly string Publisher = "ALT";
        private static readonly string Platforms = "Web";
        private static readonly bool IncludedSetting = true;
    }
}

ALT/ALT.Web.GamePlayer/Views/Home/Game.cshtml
@model  ALT.Web.GamePlayer.Models.GameCommonViewModel
@{ Layout = null;
    string pointRate = Model.GameAccess.PointRate.ToString();
    var gameDownloadURL = Model.GameSetting.DowloadURL.LastIndexOf("/") == Model.GameSetting.DowloadURL.Length - 1 ? Model.GameSetting.DowloadURL : Model.GameSetting.DowloadURL + "/";
}
<!doctype html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>@Model.GameSetting.GameCode</title>

    <link rel="stylesheet" href="@Url.Content($"~/Game/{Model.GameSetting.GameCode}/TemplateData/style.css")">
    @Scripts.Render("~/bundles/show-play-game")
    <script type="text/javascript" src="@Url.Content($"~/Game/{Model.GameSetting.GameCode}/TemplateData/CSSPlugin.js")"></script>
    <script src="@Url.Content($"~/Game/{Model.GameSetting.GameCode}/TemplateData/UnityProgress.js")"></script>
    @Styles.Render("~/Content/show-play-game")
</head>
<body class="template" style="background: url(@Url.Content($"~/Content/Images/bg/{Model.GameSetting.GameCode}.jpg")) top center;background-repeat: no-repeat;background-size: cover;">
    <div class="template-wrap clear">
        <canvas class="emscripten" id="canvas" oncontextmenu="event.preventDefault()" height="752" width="1280"></canvas>
        <br>
    </div>
    <div id="loadingBox">
        <div id="bgBar"></div>
        <div id="progressBar"></div>
        <img id="spinner" src="@Url.Content($"~/Game/{Model.GameSetting.GameCode}/TemplateData/spinner.gif")" style="display: none; margin: 0 auto" />
        <p id="loadingInfo">Loading...</p>
    </div>

    <script type='text/javascript'>
        var Module = {
            TOTAL_MEMORY: 268435456,
            errorhandler: null,			// arguments: err, url, line. This function must return 'true' if the error is handled, otherwise 'false'
            compatibilitycheck: null,
            dataUrl: "@Url.Content($"{gameDownloadURL}/{Model.GameSetting.GameCode}.data")",
            codeUrl: "@Url.Content($"{gameDownloadURL}/{Model.GameSetting.GameCode}.js")",
            memUrl: "@Url.Content($"{gameDownloadURL}/{Model.GameSetting.GameCode}.mem")",
        };

        function getConnectionString() {
            var strToken = "@Model.GameAccess.SessionCode;@Model.GameSetting.Domain";
            var strPortSerect = ";@Model.GameSetting.Port;@Model.GameAccess.Secret;assetkey";
            var connectionString = strToken + strPortSerect;
            SendMessage('GameController', 'getConnectionStringCallBack', connectionString);

            SendMessage('GameController', 'SetPointRate', "@pointRate");
        }

        function UpdatePoints(points) {
            SendMessage("GameController", "DepositCredit", points.toString());
        }


        function HandleUpdateCurrentPoint(points) {
            SendMessage("GameController", "HandleUpdateCurrentPoint", points.toString());
        }

        function UpdateCurrentPoints(points) {
            try {
                window.opener.ReceiveUpdatePointForWeb(points, '@Model.GameSetting.GameCode');
            } catch (e) {
            }
        }



        function GetSomeInfo(info) {
        }

        function OnDisconneted() {
            try {
                window.opener.OnDisconnetedForWeb(true, '@Model.GameSetting.GameCode');
            } catch (e) {

            }

        }

        jQuery(window).bind(
                     "beforeunload",
                       function (e) {
                           var activeElementTagName = e.target.activeElement.tagName;
                           if (activeElementTagName != "A" && activeElementTagName != "INPUT") {
                               OnDisconneted();
                           }
                       });
    </script>

    <script src="@Url.Content($"{gameDownloadURL}/UnityLoader.js")"></script>
</body>
</html>

ALT/ALT.Web.GamePlayer/Views/Home/Index.cshtml
@model  IEnumerable<ALT.Common.Models.GameResp>
@using ALT.Web.GamePlayer.Core;
@{
    ViewBag.Title = "Games";
    decimal point = AuthManager.AuthIdentity.Points;
    decimal pointRate = AuthManager.AuthIdentity.PointRate;
    var tokenCurrent = AuthManager.AuthIdentity.SessionCode;
    var currencyCode = AuthManager.AuthIdentity.CurrencyCode;
}
<input type="text" value="@tokenCurrent" id="tokenCurrent" hidden />
<div id="get-all-game" class="bg_load">
    <div class="header" style="min-height:1px">
        <div class="top-menu" style="height:112px">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 pull-left img-logo">
                        <img src="@Url.Content("~/Content/Images/data/logo/logo.png")" />
                    </div>
                    <div class="col-md-6">
                        <input id="ocode" value="@ALT.Web.GamePlayer.Core.AuthManager.AuthIdentity.SessionCode" hidden>
                        <input id="point-rate" value="@ALT.Web.GamePlayer.Core.AuthManager.AuthIdentity.PointRate" hidden>
                        <div class="text-right">
                            <div class="header-lang text-right pull-right" style="margin-top: -25px;">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <img src="@Url.Content("~/Content/Images/icon/flagUS.png")" />
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div style="color:white;font-size:16px;margin-top: 29px;">
                                <div>Uersname:<span>@ALT.Web.GamePlayer.Core.AuthManager.AuthIdentity.Username</span></div>
                                <div>Balance @currencyCode:<span id="balance"></span></div>
                                <div>
                                    <a class="btn btn-info btn-sm" target="_blank" href="@Url.Action("Index","GameHistory")">History</a>
                                    @Html.ActionLink("Log out", "Logout", "Account", new { token = ALT.Web.GamePlayer.Core.AuthManager.AuthIdentity.SessionCode },
                                          new { @class = "btn-signout btn btn-danger btn-sm" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class='row'>
            <nav class='col-xs-12'>
                <div class='newsnav'>
                    <div class='search'><i class="fa fa-search"></i> ALL</div>
                    <ul class='newslinks'>
                        <li>
                            @*<a href='#'>
                                    Featured Games
                                </a>*@
                            <a href='#' class="active">
                                Slots
                            </a>
                            @*<a href='#'>
                                    About
                                </a>
                                <a href='#'>
                                    Contact
                                </a>*@
                        </li>
                    </ul>
                </div>
            </nav>
            <nav class='col-xs-12'>
                <div class='searchnav'>
                    <ul>
                        <li id='filter-name'><i class="fa fa-filter" aria-label='filter by name'></i> BY NAME</li>
                        <li id='filter-date'><i class="fa fa-filter"></i> BY DATE</li>
                        <li class='search-field'>
                            <input id='article-search' placeholder='Search for an article.'>
                        </li>
                        <li class='close-search'><i class="fa fa-times"></i></li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class='row' data-bind="foreach : getAllGame ">
            <div data-bind="visible: Enable()">
                <a href='#' class='col-lg-3 col-md-4 col-sm-6 col-xs-6 col-xxs-12'>
                    <article class='style1'>
                        <input data-bind="visible : isComingsoon(), attr: {id: Code } , click:  $parent.playgame.bind($data)"
                               class="play-game" @*value="Play Game"*@ type="button" style="background: url(@Url.Content("~/Content/Images/icon/icon-play-now.png")) no-repeat;" />
                        <div data-bind="foreach : Settings">
                            <div class='coming-soon' data-bind="visible: !Enable()">
                                COMING SOON
                            </div>
                            <div class='date-new' data-bind="visible: IsNew()">
                                NEW
                            </div>
                            <div class='date-hot' data-bind="visible: IsHot()">
                                HOT
                            </div>
                        </div>
                        <div data-bind="visible : isItemGameLoading()">
                            <i class="loader fa fa-spinner"></i>
                        </div>
                        <img data-bind="attr:{src: imagePath}" height="167" width="236" />

                        <div class='content'>
                            <div class='title text-center'>
                                <span data-bind="text : Name" style="opacity:0.8"></span>
                            </div>
                        </div>
                    </article>
                </a>
            </div>
        </div>
    </div>
    <div data-bind="visible : isLoading()">
        <div class="wrapper">
            <div class="inner">
                <span>L</span>
                <span>o</span>
                <span>a</span>
                <span>d</span>
                <span>i</span>
                <span>n</span>
                <span>g</span>
            </div>
        </div>
    </div>
</div>
<div class='newsbottom'>
    <div class='to-top'><i class="fa fa-arrow-up"></i></div>
</div>

@Scripts.Render("~/bundles/signalR")
<script src="~/signalr/hubs"></script>
@Scripts.Render("~/bundles/get-all-game")